I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 98, in script call
    image bg marioland = "marioland.jpg"
  File "renpy/common/00console.rpy", line 765, in script call
    python in _console:
Exception: Sayer 'input' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 98, in script call
    image bg marioland = "marioland.jpg"
  File "renpy/common/00console.rpy", line 765, in script call
    python in _console:
  File "<string>", line 1, in script
  File "/Users/James/Desktop/renpy-6.99.14.3-sdk/renpy/ast.py", line 624, in execute
    who = eval_who(self.who, self.who_fast)
  File "/Users/James/Desktop/renpy-6.99.14.3-sdk/renpy/ast.py", line 537, in eval_who
    raise Exception("Sayer '%s' is not defined." % who.encode("utf-8"))
Exception: Sayer 'input' is not defined.

Darwin-15.6.0-x86_64-i386-64bit
Ren'Py 6.99.14.3.3347
RenPy 1.0
Thu May 31 14:05:09 2018
