I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 14, in script call
    "Nothing too scary, mind you. But it will help with making this game as fun for you as possible!"
  File "renpy/common/00console.rpy", line 765, in script call
    python in _console:
  File "game/script.rpy", line 392, in script
    $ late = true
  File "game/script.rpy", line 392, in <module>
    $ late = true
NameError: name 'true' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 14, in script call
    "Nothing too scary, mind you. But it will help with making this game as fun for you as possible!"
  File "renpy/common/00console.rpy", line 765, in script call
    python in _console:
  File "game/script.rpy", line 392, in script
    $ late = true
  File "G:\Downloadings\renpy-6.99.14.3-sdk\renpy\ast.py", line 862, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "G:\Downloadings\renpy-6.99.14.3-sdk\renpy\python.py", line 1888, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/script.rpy", line 392, in <module>
    $ late = true
NameError: name 'true' is not defined

Windows-8-6.2.9200
Ren'Py 6.99.14.3.3347
RenPy 1.0
Wed May 30 08:07:53 2018
